# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
    ]
