# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.TextField(default='Вася Пупкин, 8 912 345 67 89, Индекс ******, город ***, ул ***, дом ***, кв ***', verbose_name='Данные о покупателе'),
        ),
    ]
